[env:esp32-c6-devkitm-1]
platform = espressif32
board = esp32-c6-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = partitions_singleapp_large.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0
lib_deps = 
    ; BLE stack is included in ESP-IDF